#ifndef DATATYPES_H_INCLUDED
#define DATATYPES_H_INCLUDED

enum class OutPutFileMode
{
    CIF_OUTPUT_MODE = 0,
    GDS_OUTPUT_MODE = 1,
    MAG_OUTPUT_MODE = 2,
    MAX_OUTPUT_MODE = 3,
    ALL_OUTPUT_MODES = 4,
};



#endif // DATATYPES_H_INCLUDED
